from typing import Any, Callable, Optional
from flask import Flask

class LoginManager:
    login_view: Optional[str]

    def __init__(self, app: Flask | None = None) -> None: ...
    def init_app(self, app: Flask) -> None: ...
    def user_loader(self, callback: Callable[[str], Any]) -> Callable[[str], Any]: ...
    #def request_loader(self, callback: Callable[..., Any]) -> Callable[..., Any]: ...

def login_user(user: Any, remember: bool = False) -> None: ...
def logout_user() -> None: ...
#def current_user() -> Any: ...

class UserMixin:
    is_authenticated: bool
    is_active: bool
    is_anonymous: bool
    id: str
    #def get_id(self) -> str: ...