from flask import Flask
from typing import Any

class CKEditor:
    def __init__(self, app: Flask | None = None) -> None: ...
    def init_app(self, app: Flask) -> None: ...

def CKEditorField(*args: Any, **kwargs: Any) -> Any: ...
#def load() -> str: ...