"""added birthday

Revision ID: 03b059038c80
Revises: c1e5407a4f29
Create Date: 2025-12-17 12:24:04.791190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03b059038c80'
down_revision = 'c1e5407a4f29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('birthday', sa.String(), nullable=True))
        batch_op.drop_column('fav_color')
        batch_op.drop_column('about_author')
        batch_op.drop_column('profile_pic')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_pic', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('about_author', sa.TEXT(length=520), nullable=True))
        batch_op.add_column(sa.Column('fav_color', sa.VARCHAR(length=120), nullable=True))
        batch_op.drop_column('birthday')

    # ### end Alembic commands ###
