"""added username

Revision ID: 1938b03f92fd
Revises: ee5a7222348b
Create Date: 2025-12-11 12:33:40.303321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1938b03f92fd'
down_revision = 'ee5a7222348b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=20), nullable=False))
        batch_op.create_unique_constraint('uq_Posts_username', ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('uq_posts_username', type_='unique')
        batch_op.drop_column('username')

    # ### end Alembic commands ###
