"""Added ForeignKey

Revision ID: 9856d7458f26
Revises: eba86712bba3
Create Date: 2025-12-13 14:15:40.928436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9856d7458f26'
down_revision = 'eba86712bba3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('poster_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('uq_Posts_ForeignKey', 'users', ['poster_id'], ['id'])
        batch_op.drop_column('author')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_constraint('uq_posts_fk', type_='foreignkey')
        batch_op.drop_column('poster_id')

    # ### end Alembic commands ###
