"""removed fav_color

Revision ID: ba5c361ae551
Revises: b0b50f0b25f7
Create Date: 2025-12-10 09:49:11.090902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba5c361ae551'
down_revision = 'b0b50f0b25f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('fav_color')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fav_color', sa.VARCHAR(length=120), nullable=True))

    # ### end Alembic commands ###
