"""migration removal

Revision ID: d9efafd72e80
Revises: f4f70293b46f
Create Date: 2025-12-09 21:28:39.792635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9efafd72e80'
down_revision = 'f4f70293b46f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('password_hash')
        batch_op.drop_column('fav_color')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fav_color', sa.VARCHAR(length=120), nullable=True))
        batch_op.add_column(sa.Column('password_hash', sa.VARCHAR(length=128), nullable=True))

    # ### end Alembic commands ###
