"""edited column

Revision ID: eba86712bba3
Revises: 1938b03f92fd
Create Date: 2025-12-12 13:22:59.432441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eba86712bba3'
down_revision = '1938b03f92fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_name', sa.String(length=20), nullable=False))
        batch_op.drop_constraint(batch_op.f('uq_Posts_username'), type_='unique')
        batch_op.create_unique_constraint('uq_Posts_user_name', ['user_name'])
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=20), nullable=False))
        batch_op.drop_constraint('uq_Posts_user_name', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_Posts_username'), ['username'])
        batch_op.drop_column('user_name')

    # ### end Alembic commands ###
